
package com.xjn.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import javax.ws.rs.*;
import javax.ws.rs.core.*;
import org.apache.cxf.jaxrs.client.*;

/**
 * This class was generated by Apache CXF 2.7.18 2024-01-14T15:55:42.477+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class TitanicDataService_TitanicDataServicePort_Client {

	private static final QName SERVICE_NAME = new QName("http://xjn.com/", "TitanicDataServiceService");

	private static String webServiceUrl = "http://localhost:8080/com.xjnrs/api/titanic";

	private TitanicDataService_TitanicDataServicePort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = TitanicDataServiceService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		TitanicDataServiceService ss = new TitanicDataServiceService(wsdlURL, SERVICE_NAME);
		TitanicDataService port = ss.getTitanicDataServicePort();

		{
			System.out.println("Invoking getCountByAttribute...");
			java.lang.String _getCountByAttribute_arg0 = "Age";
			java.lang.String _getCountByAttribute_arg1 = "22";
			int _getCountByAttribute__return = port.getCountByAttribute(_getCountByAttribute_arg0,
					_getCountByAttribute_arg1);
			System.out.println("getCountByAttribute.result=" + _getCountByAttribute__return);

		}
		{
			System.out.println("Invoking getPassengerAttributes...");
			java.lang.String _getPassengerAttributes_arg0 = "Moran Mr. James";
			java.util.List<java.lang.String> _getPassengerAttributes__return = port
					.getPassengerAttributes(_getPassengerAttributes_arg0);
			System.out.println("getPassengerAttributes.result=" + _getPassengerAttributes__return);

		}

		{
			System.out.println("Invoking RS getCountByAttribute...");
			WebClient c = WebClient.create(webServiceUrl).path("count").path("Age").path("22");
			c.accept("text/plain");
			try {
				String s = c.get(String.class);
				System.out.println("getCountByAttribute.result=" + s);
			} catch (NotFoundException e) {
				System.out.println("Oops!");
			}
		}

		{
			System.out.println("Invoking RS getPassengerAttributes...");
			WebClient c = WebClient.create(webServiceUrl).path("passenger-attr").path("Moran Mr. James");
			c.accept("text/plain");
			try {
				String s = c.get(String.class);
				System.out.println("getPassengerAttributes.result=" + s);
			} catch (NotFoundException e) {
				System.out.println("Oops!");
			}
		}

		{
			System.out.println("Invoking timeapi...");
			WebClient c = WebClient.create("https://timeapi.io/api/Conversion/DayOfTheWeek").path("2021-03-14");
			c.accept("application/json");
			try {
				String s = c.get(String.class);
				System.out.println("DayOfTheWeek=" + s);
			} catch (NotFoundException e) {
				System.out.println("Oops!");
			}
		}

		System.exit(0);
	}

}
