
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xjn.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2024-01-14T15:55:42.506+08:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "TitanicDataServiceService",
                      portName = "TitanicDataServicePort",
                      targetNamespace = "http://xjn.com/",
                      wsdlLocation = "file:/C:/Users/11422/Desktop/miniproject/com.xjnClient/webapp/wsdl/titanicdataservice.wsdl",
                      endpointInterface = "com.xjn.TitanicDataService")
                      
public class TitanicDataServiceImpl implements TitanicDataService {

    private static final Logger LOG = Logger.getLogger(TitanicDataServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.xjn.TitanicDataService#getCountByAttribute(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public int getCountByAttribute(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getCountByAttribute");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = -1873075826;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xjn.TitanicDataService#getPassengerAttributes(java.lang.String  arg0 )*
     */
    public java.util.List<java.lang.String> getPassengerAttributes(java.lang.String arg0) { 
        LOG.info("Executing operation getPassengerAttributes");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal996434626";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
