package com.xjn.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2024-01-14T15:55:42.512+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://xjn.com/", name = "TitanicDataService")
@XmlSeeAlso({ObjectFactory.class})
public interface TitanicDataService {

    @WebMethod(action = "urn:GetCountByAttribute")
    @RequestWrapper(localName = "getCountByAttribute", targetNamespace = "http://xjn.com/", className = "com.xjn.GetCountByAttribute")
    @ResponseWrapper(localName = "getCountByAttributeResponse", targetNamespace = "http://xjn.com/", className = "com.xjn.GetCountByAttributeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getCountByAttribute(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod(action = "urn:GetPassengerAttributes")
    @RequestWrapper(localName = "getPassengerAttributes", targetNamespace = "http://xjn.com/", className = "com.xjn.GetPassengerAttributes")
    @ResponseWrapper(localName = "getPassengerAttributesResponse", targetNamespace = "http://xjn.com/", className = "com.xjn.GetPassengerAttributesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getPassengerAttributes(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
